services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8001:8001"
    environment:
      - API_TOKEN=${API_TOKEN}
      - FASTAPI_URL=http://fastapi:8001
      - PYTHONPATH=/app
    volumes:
      - ./src/server:/app/server
    networks:
      - app_network
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8503:8503"
    environment:
      - FASTAPI_URL=http://fastapi:8001
      - MISTRAL_API_KEY=
      - API_TOKEN=
      - PYTHONPATH=/app
    depends_on:
      - fastapi
    volumes:
      - ./src/client:/app/client
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge